Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

# Added a default URL path to my 'workblog' app.
urlpatterns = [
    path('', include('workblog.urls')),
    path('admin/', admin.site.urls),
]

workblog/urls.py
from django.urls import path

from . import views

app_name = 'workblog'
urlpatterns = [
    path('', views.index, name="index"),
    path('projects', views.projects, name="projects"),
    path('blog', views.blog, name='blog'),
]

workblog/models.py
from django.db import models

# Model, that represents daily entry of my blog.
# It has:
# 1. Date and time (auto set)
# 3. Things done
# 4. Tomorrow's work plan

class Daily(models.Model):
    pub_date = models.DateTimeField()
    work_done = models.CharField(max_length = 1000)
    tomorrow_work = models.CharField(max_length = 500)

    # If objects of Daily will be called, they will be represented by the value of variable 'things_learned'. 
    def __str__(self):
        return self.tomorrow_work

class Project(models.Model):
    title = models.CharField(max_length = 50)
    github_url = models.CharField(max_length = 100)
    site_url = models.CharField(max_length = 100)
    description = models.TextField()

workblog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from workblog.models import *

# The only view right now is a funciton 'index'.
# It returns a HttpResponse, and loads a html template, and includes variable dailys.
# Variable dailys contains all instances of the class Daily that are saved in the database.

def projects(request):
    projects = Project.objects.all()
    return render(request, 'workblog/projects.html', {'projects':projects})

def index(request):
    return render(request, 'workblog/index.html')

def blog(request):
    dailys = Daily.objects.all().order_by('-pub_date')
    return render(request, 'workblog/detail.html', {'dailys': dailys})

workblog/templates/workblog/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Work Blog</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'workblog/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="This page contains summary of my work on a daily basis."> 
        <meta name="keywords" content="programming, work log, work blog, improvement, diary, work diary">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- Custom font -->
        <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    </head>
    <body>
        <!-- Navigation bar (left side) -->
        <nav>
            <ul>
                <!-- Orange button to homesite -->
                <li id="home"><a id="home_btn" href="{% url 'workblog:index' %}">Rok Klančar</a></li>
                <li><a href="{% url 'workblog:projects' %}">Projects</a></li>
                <li><a href="{% url 'workblog:blog' %}">Work Blog</a></li>
            </ul>
        </nav>
        <!-- Content (right side) -->
        <main>
            <!-- Content that is disclaiming the purpose of this page -->
            <article id="disclaimer">
                <p>
                    This is my work blog. It serves me to keep track of my working habits and progress.
                </p>
            <!-- Main content. Generated by Django -->
            </article id="rows">
            {% for daily in dailys %}
            <article>
                <h3>{{ daily.pub_date }}</h3>
                <p><em>Today's work</em>: {{ daily.work_done }}</p>
                <p><em>Plan for tomorrow</em>: {{ daily.tomorrow_work }}</p>
                <hr>
            </article>
            {% endfor %}
        </main>
    </body>
</html>

workblog/templates/workblog/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Rok Klančar</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'workblog/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Homepage"> 
        <meta name="keywords" content="programming, rok, rok klančar, klancar, work blog">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- Custom font -->
        <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    </head>
    <body>
        <!-- Navigation bar (left side) -->
        <nav>
            <ul>
                <!-- Orange button to homesite -->
                <li id="home"><a id="home_btn" href="{% url 'workblog:index' %}">Rok Klančar</a></li>
                <li><a href="{% url 'workblog:projects' %}">Projects</a></li>
                <li><a href="{% url 'workblog:blog' %}">Work Blog</a></li>
            </ul>
        </nav>
        <!-- Content (right side) -->
        <main>
            <!-- Content that is disclaiming the purpose of this page -->
            <article id="disclaimer">
                <p>
                    Hi! My name is Rok and I am a web developer. <br>
                    Working from a Xubuntu machine, most familliar with the Django framework. Also use PHP for backend. <br>
                    Use HTML and CSS, getting familiar with JavaScript. <br>
                    Use SQLite, PostgreSQL and MySQL.
                </p>
                <p>
                    <a href="https://github.com/HyoMiYing" target="_blank">github</a>
                </p>
                <p>
                    You can reach me at <strong>rklancar [at] gmail [dot] com</strong>.
                </p>
        </main>
    </body>
</html>

workblog/templates/workblog/projects.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Projects</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'workblog/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="My projects"> 
        <meta name="keywords" content="programming, project, learning">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- Custom font -->
        <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    </head>
    <body>
        <!-- Navigation bar (left side) -->
        <nav>
            <ul>
                <!-- Orange button to homesite -->
                <li id="home"><a id="home_btn" href="{% url 'workblog:index' %}">Rok Klančar</a></li>
                <li><a href="{% url 'workblog:projects' %}">Projects</a></li>
                <li><a href="{% url 'workblog:blog' %}">Work Blog</a></li>
            </ul>
        </nav>
        <!-- Content (right side) -->
        <main>
            <!-- Content that is disclaiming the purpose of this page -->
            {% if projects %}
                {% for project in projects %}
                <article>
                    <h2 class="projecttitle">{{ project.title }}</h3>
                    <p><a href="{{ project.github_url }}" target="_blank">GitHub</a></p>
                    <p><a href="{{ project.site_url }}" target="_blank">Live site</a></p>
                    <br>
                    <p>{{ project.description }}</p>
                    <hr class="projecthr">
                </article>
                {% endfor %}
            {% else %}
            <article id="disclaimer">
                <p>
                    No projects yet to show.
                </p>
            {% endif %}
        </main>
    </body>
</html>